services:
  elasticsearch:
    container_name: elasticsearch-container
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    restart: unless-stopped
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana-container
    image: docker.elastic.co/kibana/kibana:9.3.2
    ports:
      - "5601:5601"
    restart: unless-stopped
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash-container
    image: docker.elastic.co/logstash/logstash:9.3.2
    restart: unless-stopped
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - back-volume:/app/logs/spring
      - caddy-volume:/app/logs/caddy
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-volume:
  back-volume:
    external: true
    name: back-volume
  caddy-volume:
    external: true
    name: caddy-volume
