services:
  front:
    container_name: orion-microcrm-front-container
    build:
      context: .
      dockerfile: Dockerfile
      target: front
    image: orion-microcrm-front:latest
    volumes:
      - caddy-volume:/app/log/
    ports:
      - "80:80"
    restart: unless-stopped

  back:
    container_name: orion-microcrm-back-container
    build:
      context: .
      dockerfile: Dockerfile
      target: back
    image: orion-microcrm-back:latest
    volumes:
      - back-volume:/app/logs
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  back-volume:
    name: back-volume
  caddy-volume:
    name: caddy-volume
