sonar.organization=victorhazebrouck
sonar.projectKey=victorhazebrouck_ocl-p7

sonar.sources=back/src,front/src
sonar.java.binaries=back/build/classes

sonar.coverage.jacoco.xmlReportPaths=back/build/reports/jacoco/test/jacocoTestReport.xml
sonar.javascript.lcov.reportPaths=front/coverage/microcrm/lcov.info
