input {
    http {
        port => 5000
        codec => json_lines
        tags => ["dora"]
    }

    file {
        path => "/app/logs/spring.log"
        codec => json
        tags => ["spring"]
    }

    file {
        path => "/app/logs/caddy/*.log"
        codec => json
        tags => ["caddy"]
    }
}

filter {
    if "dora" in [tags] {
        date {
            match => [ "datetime", "ISO8601" ]
        }
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "%{tags}"
    }
    stdout {
        codec => rubydebug
    }
}
